version: 2
orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    working_directory: /go/src/github.com/kairintyo/circle-ci-test
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - slack/status
